### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by joshtharakan** [web3j/web3j-corda#32]
I am getting the below error message while trying to install using the command
 `curl -L https://getcorda.web3j.io | bash`

error message
``` 
 2019-12-19 14:12:49 ⌚  Josephs-MacBook-Pro-2 in ~/Development/web3corda
○ → curl -L https://getcorda.web3j.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  3710  100  3710    0     0   1408      0  0:00:02  0:00:02 --:--:--  4211
Downloading web3j-corda ...
Looks like there was an error while trying to download web3j-corda

```
OS : Mac OS Mojave V 10.14.6

**Comment by Puneetha17** [comment]
Fixed with the latest 0.2.8 release, please do verify.

**Comment by xaviarias** [comment]
Hi @joshtharakan , is still an issue for you or I can close it?

**Comment by joshtharakan** [comment]
I have successfully installed and hence closing the bug.
